# Tiers config

# How many players need to join to increase a tier.
tierInterval: 1

# How many blocks to increase border radius by per tier.
tierSize: 500

# For LuckPerms integration: what track should we place tier ranks in?
# You should create this track yourself!
# No need to modify if not using LuckPerms.
trackName: "tiers"

