name: Tiers
main: net.williserver.tiers.TiersPlugin
version: 1.0
api-version: 1.20
softdepend: [LuckPerms]

commands:
  tiers:
    description: Execute tiers function helpers.
    usage: "Usage: /tiers [get | set (size) | help]"

permissions:
  tiers.set:
    description: Allows /tiers set
    default: op
  