name: Tiers
main: net.williserver.tiers.TiersPlugin
version: 1.0
api-version: 1.21
softdepend: [LuckPerms]

commands:
  tiers:
    description: Execute tiers function helpers.
    usage: "Usage: /tiers [get | set (size) | inc | dec | help]"

permissions:
  tiers.set:
    description: Allows /tiers set
    default: op
  tiers.inc:
    description: Allows /tiers inc
    default: op
  tiers.dec:
    description: Allows /tiers dec
    default: op

  